apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vyasa-ingress
  namespace: vyasa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: vyasa.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vyasa-api-service
            port:
              number: 80
