apiVersion: v1
kind: Service
metadata:
  name: vyasa-api-service
  namespace: vyasa
  labels:
    app: vyasa-api
spec:
  selector:
    app: vyasa-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
